sudo: required
language: cpp
services:
  - docker
before_install:
  - docker build -t kamiizumi/mangos-build:latest .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push kamiizumi/mangos-build:latest